Vns.Web/Areas/Portal/Components/HeaderPortalViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace Vns.Web.Areas.Portal.Components
{
    public class HeaderPortalViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(string pageName, string actionName)
        {
            ViewData["PageName"] = pageName;
            ViewData["Action"] = actionName;
            return View();
        }
    }
}

Vns.Web/Areas/Portal/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Vns.Core.Commons;
using Vns.Core.Commons.BaseResponse;
using Vns.Core.Commons.Enum;
using Vns.Core.Commons.Paging;
using Vns.Infrastructure.ModelView.ArticleModel;
using Vns.Infrastructure.Services.IRepository;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Vns.Web.Areas.Portal.Controllers
{
    public class ArticleController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IArticleRepository _articleRepository;

        public ArticleController(IUnitOfWork unitOfWork, IArticleRepository articleRepository)
        {
            _unitOfWork = unitOfWork;
            _articleRepository = articleRepository;
        }

        // GET: /<controller>/
        public IActionResult Index(string search = "", int pageIndex = 0)
        {
            ViewData["Title"] = "Bài Viết";
            ArticleRequest request = new ArticleRequest()
            {
                Keyword = search == "" ? null : search,
                PageIndex = pageIndex,
                CategoryId = null,
                Status = EStatus.All
            };
            IPagedList<ArticleDto> articles = _articleRepository.GetList(request);
            
            return View(articles);
        }

        public IActionResult Detail(int? id) {
            ViewData["Title"] = "Bài Viết";
            ViewData["Action"] = "Chi tiết";
            var article = _articleRepository.GetDetail(id);
            return View(article);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Bài Viết";
            ViewData["Action"] = "Tạo mới";
            return View();
        }

        [HttpGet]
        public JsonResult GetCategories()
        {
            return Json(_unitOfWork.Category.GetAll());
        }


        [HttpPost]
        public JsonResult CreateArticle(ArticleDto article)
        {
            DetailResponse<ArticleDto> result = new DetailResponse<ArticleDto>();
            if (article.Title == null)
            {
                result = new DetailResponse<ArticleDto>
                {
                    Status = false,
                    Data = article,
                    Message = ErrorConstant.Get(MessageCode.BE0003)

                };
                return Json(result);
            }

            if (article.Description == null)
            {
                result = new DetailResponse<ArticleDto>
                {
                    Status = false,
                    Data = article,
                    Message = ErrorConstant.Get(MessageCode.BE0004)

                };
                return Json(result);
            }
    
            result = _articleRepository.Insert(article);
            return Json(result);
        }

        [HttpPost]
        public JsonResult ActiveArticle(int? id)
        {
            DetailResponse<int> response = new DetailResponse<int>();
            response = _articleRepository.Approve(id);
            return Json(response);
        }

        [HttpPost]
        public JsonResult DeleteArticle(int? id)
        {
            return Json(_articleRepository.Remove(id));
        }
    }
}

Vns.Web/Areas/Portal/Views/Article/Create.cshtml
@await Component.InvokeAsync("HeaderPortal", new { pageName = ViewData["Title"], actionName = ViewData["Action"] })
<section class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Tạo mới bài viết</h3>
            </div>
            
            <!-- form start -->
            <form  method="post" enctype="multipart/form-data" id="article-form">
              <div class="box-body">

                <div id="title-form-group" class="form-group" >
                  <label for="titleArticle">Tiêu đề bài viết</label>
                  <input type="text" class="form-control" id="title" placeholder="Tiêu đề bài viết" name="title" />
                  <span class="help-block" id="notification-title-input"></span>
                </div>

                <div class="form-group">
                  <label>Chọn loại bài viết</label>
                  <select id="categories" class="form-control"></select>
                </div>

                <div class="form-group">
                    <label>Loại hiển thị</label>
                    <select id="display-home" class="form-control">
                      <option value="DE">Mặc định</option>
                      <option value="FE">Hiển thị phần nổi bật</option>
                      <option value="TR">Hiển thị trending</option>
                    </select>
                </div>

                <div id="image-form-group" class="form-group">
                  <label for="image">Upload hình ảnh</label>
                  <input type="file" id="images" accept="image/*" name="image">
                  <p class="help-block">Hình ảnh</p>
                  <span class="help-block" id="notification-image-input"></span>
                </div>


                <div id="description-form-group" class="form-group" >
                  <label>Mô tả ngắn</label>
                  <textarea class="form-control" rows="3" placeholder="Enter ..." id="description"></textarea>
                  <span class="help-block" id="notification-description-input"></span>
                </div>

                <div id="content-form-group" class="form-group">
                  <label>Nội dung</label>
                  <div id="editor"></div>
                  <span class="help-block" id="notification-content-input"></span>
                </div>
              </div>
              <div class="box">
            <div class="box-header">
              <h3 class="box-title">HashTags</h3>
            </div>
            <div class="box-body">
              <div class="input-group margin">
                  <input type="text" class="form-control" id="input-tag">
                      <span class="input-group-btn">
                        <button type="button" class="btn btn-info btn-flat" id="put-tag">Thêm</button>
                      </span>
                </div>
                <div class="margin" id="list-tags"></div>
            </div>
            <!-- /.box-body -->
          </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a class="btn btn-primary" id="btn-submit">Submit</a>
              </div>
            </form>
          </div>
            <!-- /.box -->
        </div>
        <div class="col-md-4">
          <div class="box box-primary">
              <img id="img-loader" class="img-responsive" />    
          </div>
           
        </div>
    </div>
    
</section>

@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
    <script type="text/javascript">
        ClassicEditor.create(document.querySelector('#editor'), {
            ckfinder: {
                uploadUrl: '/media/EditorUpload'
            },
            toolbar: ['ckfinder', 'imageUpload', '|', 'heading', '|', 'bold', 'italic', '|', 'undo', 'redo']
            })
            .catch(function (error) {
                console.error(error);
            });
    </script>

    
    <script>
      var tagsData = [];
      var categories = [];
      $(function () {

          var img = $("#img-loader");
          img.attr("src", noImage);


          // get categories article
          $.ajax({
            url: 'GetCategories',
            type: "GET",
            dataType: 'json', // added data type
            success: function (data) {
              console.log(data);
              if (data){
                data.forEach(item => {
                  $('#categories').append("<option value='"+ item.id +"'>" + item.description + " </option>")
                })
              }
            },
            error: function (passParams) {
                console.log(passParams);
            }
          });

          $("#images").change((e) => {
            var selectedFiles = $('#images').prop('files');
            if (selectedFiles.length === 0){
              img.attr("src", noImage );
            } else {
              encodeImageFileAsURL(selectedFiles, (base64) => {
                img.attr("src",base64);
              });
            }
          });

          $("#btn-submit").click((e) => {
              e.preventDefault();
              
              if (validateForm()){
                var image = $('#images').prop('files')[0];
                  uploadImages(image, (url) => {
                    var content = CKEDITOR.instances["editor1"].getData();
                    var title = $('#title').val();
                    var description = $('#description').val();
                    var tags = tagsData.map(item => { return { Name: item }});
                    var categoryId = $('#categories').val();
                    var display = $('#display-home').val();
                    

                    var article = {
                      Content: content,
                      Title: title,
                      Description: description,
                      CategoryId: categoryId,
                      Images: {
                        Url: url
                      },
                      Tags: tags,
                      IsTrending: display === "TR" ? true : false,
                      IsFeatured: display === "FE" ? true : false
                    };
                
                    $.ajax({
                      url: 'CreateArticle',
                      data: article,
                      type: "POST",
                      success: function (data) {
                        window.location.href = 'Index';
                      },
                      error: function (passParams) { }
                    });
                });
              }
          });


          $("#put-tag").click(e => {
            var tag = $("#input-tag");
            if (tag.val()) {
              addTag(tag.val())
            }
            tag.val("");
          });

          var validateForm = () => {
            var isValid = true;

            var title = $("#title").val();
            var description = $("#description").val();
            var content = CKEDITOR.instances["editor1"].getData();
            var selectedFiles = $('#images').prop('files');

            if (!title){
              isValid = false;
              invalidForm("title-form-group");
              $('#notification-title-input').text('Tiêu đề bài viết không được để trống');
            } else {
              validForm("title-form-group");
              $('#notification-title-input').text('');
            }

            if (!description){
              isValid = false;
              invalidForm('description-form-group');
              $('#notification-description-input').text('Mô tả bài viết không được để trống');
            } else {
              validForm('description-form-group');
              $('#notification-description-input').text('');
            }

            if (!content){
              isValid = false;
              invalidForm('content-form-group');
              $('#notification-content-input').text('Nôi dung bài viết không được để trống');
            } else {
              validForm('content-form-group');
              $('#notification-content-input').text('');
            }

            if (selectedFiles.length === 0){
                isValid = false;
                invalidForm('image-form-group');
                $('#notification-image-input').text('Hình ảnh cho bài viết là bắt buộc');
            } else {
              validForm('image-form-group');
              $('#notification-image-input').text('');
            }
            
            return isValid;
          }

          var postArticle = (article) => {
            $.ajax({
                url: 'CreateArticle',
                data: JSON.stringify({article: article}),
                type: "POST",
                dataType: 'json',
                contentType: "application/json; charset=utf-8",  
                success: function (data) {
                  
                  console.log(data);
                },
                error: function (passParams) {
                    debugger;
                }
            });
          }
      });

      var loadTags = () => {
        if (tagsData) {
          refreshTags();
          tagsData.forEach((item, index) => {
            $('#list-tags').append("<div class='btn-group' style='margin: 0px 5px 0px 0px;'> <a class='btn btn-info' >" + item + "<button type='button' class='close' style='margin: -10px -10px 0px 10px;' onclick='removeTag("+index+")'>&times;</button></a> </div>");
          });
        }
        
      }

      var removeTag = (index) => {
        if (index > -1) {
          tagsData.splice(index, 1);
        }
        loadTags();
      }
        
      var refreshTags = () => {
          const listTag = document.getElementById("list-tags");
          listTag.textContent = '';
        }

      var addTag = (tag) => {
        tag = tag.trim();
        if (!tagsData.includes(tag) && tagsData.length <= 6) {
          tagsData.push(tag);
        }
        loadTags();
      }
    </script>

}

Vns.Web/Areas/Portal/Views/Article/Detail.cshtml
<!-- Content Header (Page header) -->
@await Component.InvokeAsync("HeaderPortal", new { pageName = ViewData["Title"], actionName = ViewData["Action"] })
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tạo mới bài viết</h3>
                </div>

                <!-- form start -->
                <form method="post" enctype="multipart/form-data" id="article-form">
                    <div class="box-body">

                        <div id="title-form-group" class="form-group">
                            <label for="titleArticle">Tiêu đề bài viết</label>
                            <input type="text" class="form-control" id="title" placeholder="Tiêu đề bài viết" name="title" />
                            <span class="help-block" id="notification-title-input"></span>
                        </div>

                        <div class="form-group">
                            <label>Chọn loại bài viết</label>
                            <select id="categories" class="form-control"></select>
                        </div>

                        <div class="form-group">
                            <label>Loại hiển thị</label>
                            <select id="display-home" class="form-control">
                                <option value="DE">Mặc định</option>
                                <option value="FE">Hiển thị phần nổi bật</option>
                                <option value="TR">Hiển thị trending</option>
                            </select>
                        </div>

                        <div id="image-form-group" class="form-group">
                            <label for="image">Upload hình ảnh</label>
                            <input type="file" id="images" accept="image/*" name="image">
                            <p class="help-block">Hình ảnh</p>
                            <span class="help-block" id="notification-image-input"></span>
                        </div>


                        <div id="description-form-group" class="form-group">
                            <label>Mô tả ngắn</label>
                            <textarea class="form-control" rows="3" placeholder="Enter ..." id="description"></textarea>
                            <span class="help-block" id="notification-description-input"></span>
                        </div>

                        <div id="content-form-group" class="form-group">
                            <label>Nội dung</label>
                            <div id="editor"></div>
                            <span class="help-block" id="notification-content-input"></span>
                        </div>
                    </div>
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">HashTags</h3>
                        </div>
                        <div class="box-body">
                            <div class="input-group margin">
                                <input type="text" class="form-control" id="input-tag">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info btn-flat" id="put-tag">Thêm</button>
                                </span>
                            </div>
                            <div class="margin" id="list-tags"></div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a class="btn btn-primary" id="btn-submit">Submit</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
        <div class="col-md-4">
            <div class="box box-primary">
                <img id="img-loader" class="img-responsive" />
            </div>
        </div>
    </div>
</section>

Vns.Web/Areas/Portal/Views/Article/Index.cshtml
@model Vns.Core.Commons.Paging.IPagedList<Vns.Infrastructure.ModelView.ArticleModel.ArticleDto>

@await Component.InvokeAsync("HeaderPortal", new { pageName = ViewData["Title"], actionName = ViewData["Action"] })

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="row">
                        <div class="col-md-10"><h3 class="box-title">Danh sách bài viết</h3></div>
                        <div class="col-md-2"><p><a asp-controller="Article" asp-action="Create">Tạo Mới</a></p></div>
                    </div>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                @if (Model.Count > 0)
                                {
                                    <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">#</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Tiêu đề</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Mô Tả</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Trạng thái</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var article in Model)
                                            {
                                                <tr role="row" class="odd">
                                                    <td class="sorting_1">@article.Id</td>
                                                    <td>@article.Title</td>
                                                    <td>@article.Description</td>
                                                    <td>
                                                        @if (article.Status == true) {
                                                            <p>Đã kích hoạt</p>
                                                        } else {
                                                            <p>Chưa kích hoạt</p>
                                                        }
                                                    </td>
                                                    <td style="width: 115px">
                                                        <div class="btn-group">
                                                            <button type="button" class="btn btn-danger">Action</button>
                                                            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                                <span class="caret"></span>
                                                                <span class="sr-only">Toggle Dropdown</span>
                                                            </button>
                                                            <ul class="dropdown-menu" role="menu">
                                                                @if (article.Status == false) { 
                                                                    <li>
                                                                        <li><a onclick="activeArticle(@article.Id)">Kích hoạt</a></li>
                                                                    </li> 
                                                                }
                                                                <li><a onclick="window.location.href='article/detail?id=@article.Id'">Xem</a></li>
                                                                <li><a onclick="removeArticle(@article.Id)">Xoá</a></li>
                                                            </ul>
                                                        </div>
                                                        
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">#</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Tiêu đề</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="2" colspan="1">Mô Tả</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Trạng thái</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                } else
                                {
                                    <p>Chưa có bài viết nào <a asp-controller="Article" asp-action="Create">Tạo Mới</a></p>
                                }
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-5"><div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div>
                            <div class="col-sm-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                                        <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                                        <li class="paginate_button"><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                                        <li class="paginate_button"><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                                        <li class="paginate_button"><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                                        <li class="paginate_button"><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                                        <li class="paginate_button"><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                                        <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    <!-- Modal -->
    
</section>
<!-- /.content -->




@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js"></script>
    <script>
        $(function () {
            
        });

        var activeArticle = (id) => {
            $.ajax({
                url: 'ActiveArticle',
                data: { id: id },
                type: "POST",
                success: function (data) {
                    location.reload();
                },
                error: function (passParams) {
                    console.log(passParams);
                }
            });
        }

        var removeArticle = (id) => {
            $.ajax({
                url: 'DeleteArticle',
                data: { id: id },
                type: "POST",
                success: function (data) {
                    location.reload();
                },
                error: function (passParams) {
                    console.log(passParams);
                }
            });
        }

    </script>
}